"project_id": "506724"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  [
    {
      "source": "locales/en.yml",
      "translation": "locales/%two_letters_code%.yaml",
      "type": "yaml",
    },
  ]
