name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating an issue messages....We are working on it to fix this issue'
        pr-message: "Hi there! Thanks for contributing on the file and sending the pull request....I'll check it and merge it has no issue"
